language: php
php:
  - 5.4
  - 5.5 
  - 5.6
  - 7
  - hhvm 

script:
  - composer update 
  - phpunit --coverage-clover=coverage.xml --colors=auto ./tests/AllTests.php
after_success:
  - bash <(curl -s https://codecov.io/bash)